Created/Accessed After in Clear Cache
BCG-X-Official/artkit pull request #30
Opened 2024-06-24 20:34 UTC by betcherj

- [x] Have you followed the guidelines in our [Contributor Guide](https://bcg-x-official.github.io/artkit/contributor_guide/how_to_contribute.html) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/BCG-X-Official/artkit/pulls) for the same update/change?

## Issue number and link:
#23 
https://github.com/BCG-X-Official/artkit/issues/23

2024-06-24 22:14 UTC, breakbotz commented
@betcherj please label this PR!

2024-06-24 22:41 UTC, rgriff23 approved these changes

2024-06-24 22:51 UTC, rgriff23 requested changes
@betcherj please add back the newlines to following 3 files to comply with black formatting, then this should be good to go:

- `src/artkit/model/base/_adapter.py`
- `src/artkit/model/llm/base/_adapter.py`
- `src/artkit/model/test/artkit_test/model/cache/test_cache.py`

2024-06-25 00:46 UTC, seanggani commented
Thank you for submitting a PR @betcherj! Next time, please create a new branch with the naming convention outlined in the Contributing guide, thank you!
<img width="868" alt="Screenshot 2024-06-24 at 7 46 05 PM" src="https://github.com/BCG-X-Official/artkit/assets/60366518/bc013ed0-d829-4fbf-859a-78baadd5ce05">

2024-06-25 19:53 UTC, rgriff23 approved these changes

2024-06-25 21:03 UTC, merged